import sys
import json
from pathlib import Path
from datetime import datetime

# Ensure backend root is in python path
backend_dir = Path(__file__).resolve().parent.parent
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

from app.core.database import SessionLocal, Base, engine
from app.models.medical_image import MedicalScan, ScanFinding, AnalysisAuditLog
from app.models.user import User

def seed_data():
    db = SessionLocal()
    try:
        # 1. Initialize Tables
        print("Ensuring tables are initialized...")
        Base.metadata.create_all(bind=engine)

        # 2. Check if a demo user already exists
        demo_user = db.query(User).filter(User.email == "demo@medivision.ai").first()
        if not demo_user:
            print("Creating demo user...")
            demo_user = User(
                full_name="Dr. Demo Radiologist",
                email="demo@medivision.ai",
                hashed_password="demo_hashed_password_placeholder", # Not actually authenticated
                role="clinician"
            )
            db.add(demo_user)
            db.commit()
            db.refresh(demo_user)
        else:
            print("Demo user already exists.")

        # Clear previous demo scans to prevent duplicate seeds
        existing_demo_scans = db.query(MedicalScan).filter(MedicalScan.user_id == demo_user.id).all()
        for scan in existing_demo_scans:
            db.delete(scan)
        db.commit()
        print("Cleared existing demo scans.")

        # 3. Seed Sample Scans
        sample_scans = [
            {
                "filename": "demo_chest_xray_normal.png",
                "modality": "X-Ray",
                "patient_id": "PT-4091",
                "prediction_class": "NORMAL",
                "confidence_score": 0.985,
                "findings_summary": "Clear lung fields with no acute consolidation.",
                "original_url": "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=400&q=80",
                "heatmap_url": None,
                "overlay_url": None,
                "ai_explanation": "Normal spatial attention across cardiac and pulmonary regions.",
                "model_name": "efficientnet_b0",
                "processing_time_ms": 320.0,
                "status": "completed",
                "medical_report": {
                    "summary": "Radiographic evaluation of chest scan shows no evidence of active acute consolidation.",
                    "findings": "Normal bronchovascular markings. Clear costophrenic angles. Lungs are well inflated.",
                    "interpretation": "Negative for active chest pathology.",
                    "recommendations": ["Routine clinical follow-up as indicated."],
                    "disclaimer": "This report is generated by an artificial intelligence system (MediVision AI) for decision-support purposes only."
                },
                "findings_list": [
                    {
                        "label": "Normal Lung Fields",
                        "body_region": "Pulmonary Fields",
                        "severity": "normal",
                        "confidence": 0.98,
                        "location_description": "Bilateral lung zones",
                        "icd10_hint": "Z00.00"
                    }
                ]
            },
            {
                "filename": "demo_ct_head_hemorrhage.png",
                "modality": "CT",
                "patient_id": "PT-9021",
                "prediction_class": "HEMORRHAGE",
                "confidence_score": 0.912,
                "findings_summary": "Hyperdensity noted in left frontal lobe consistent with acute parenchymal hemorrhage.",
                "original_url": "https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=400&q=80",
                "heatmap_url": None,
                "overlay_url": None,
                "ai_explanation": "Focal high attenuation attention highlighted in coordinates X:12, Y:44.",
                "model_name": "gemini-1.5-flash",
                "processing_time_ms": 1150.0,
                "status": "completed",
                "medical_report": {
                    "summary": "Non-contrast Head CT demonstrates acute left frontal lobe intraparenchymal hematoma.",
                    "findings": "A hyperdense focal lesion measuring 2.4cm is identified in the left frontal lobe. Surrounding vasogenic edema noted.",
                    "interpretation": "Acute left frontal intraparenchymal hemorrhage with mild local mass effect.",
                    "recommendations": ["Immediate neurosurgical consultation", "Strict blood pressure controls", "Follow-up non-contrast head CT in 6 hours"],
                    "disclaimer": "This report is generated by an artificial intelligence system (MediVision AI) for decision-support purposes only.",
                    "qualitative_confidence": "high",
                    "confidence_justification": "Clear hyperdense presentation with classic edema margins."
                },
                "findings_list": [
                    {
                        "label": "Intraparenchymal Hematoma",
                        "body_region": "Left Frontal Lobe",
                        "severity": "critical",
                        "confidence": 0.91,
                        "location_description": "Left cerebral hemisphere frontal cortical/subcortical interface",
                        "icd10_hint": "I61.1"
                    }
                ]
            },
            {
                "filename": "demo_mri_spine_herniation.png",
                "modality": "MRI",
                "patient_id": "PT-1102",
                "prediction_class": "DISC_HERNIATION",
                "confidence_score": 0.845,
                "findings_summary": "Posterior disc protrusion at L4-L5 level causing mild central canal stenosis.",
                "original_url": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=400&q=80",
                "heatmap_url": None,
                "overlay_url": None,
                "ai_explanation": "Intervertebral disc interface compression detected.",
                "model_name": "gemini-1.5-flash",
                "processing_time_ms": 1820.0,
                "status": "completed",
                "medical_report": {
                    "summary": "Lumbar spine MRI reveals disc herniation at L4-L5 causing neural encroachment.",
                    "findings": "L4-L5 disc shows posterior herniation of 4mm, mildly compressing the ventral aspect of the dural sac. L5-S1 is normal.",
                    "interpretation": "L4-L5 posterior disc protrusion with mild spinal canal stenosis.",
                    "recommendations": ["Physical therapy trial", "Conservative pain management", "Neurosurgical review if radiculopathy worsens"],
                    "disclaimer": "This report is generated by an artificial intelligence system (MediVision AI) for decision-support purposes only.",
                    "qualitative_confidence": "moderate",
                    "confidence_justification": "Clear visual protrusion on sagittal T2 views but axial margins show mild artifact."
                },
                "findings_list": [
                    {
                        "label": "Disc Protrusion",
                        "body_region": "L4-L5 Lumbar Spine",
                        "severity": "moderate",
                        "confidence": 0.85,
                        "location_description": "L4-L5 posterior intervertebral disc interface",
                        "icd10_hint": "M51.26"
                    }
                ]
            }
        ]

        for scan_data in sample_scans:
            print(f"Seeding scan: {scan_data['filename']}...")
            scan = MedicalScan(
                user_id=demo_user.id,
                filename=scan_data["filename"],
                modality=scan_data["modality"],
                patient_id=scan_data["patient_id"],
                prediction_class=scan_data["prediction_class"],
                confidence_score=scan_data["confidence_score"],
                findings_summary=scan_data["findings_summary"],
                original_url=scan_data["original_url"],
                heatmap_url=scan_data["heatmap_url"],
                overlay_url=scan_data["overlay_url"],
                ai_explanation=scan_data["ai_explanation"],
                medical_report_json=json.dumps(scan_data["medical_report"]),
                model_name=scan_data["model_name"],
                processing_time_ms=scan_data["processing_time_ms"],
                status=scan_data["status"]
            )
            db.add(scan)
            db.commit()
            db.refresh(scan)

            # Seed structured findings for this scan
            for f_data in scan_data["findings_list"]:
                finding = ScanFinding(
                    scan_id=scan.id,
                    label=f_data["label"],
                    body_region=f_data["body_region"],
                    severity=f_data["severity"],
                    confidence=f_data["confidence"],
                    location_description=f_data["location_description"],
                    icd10_hint=f_data["icd10_hint"]
                )
                db.add(finding)

            # Seed mock audit log
            audit_prompt = f"System Instructions: Synthesize clinical data. Modality: {scan.modality}. Patient: {scan.patient_id}."
            db_audit = AnalysisAuditLog(
                scan_id=scan.id,
                prompt_text=audit_prompt,
                model_name=scan.model_name,
                model_version="2.0.0",
                gradcam_parameters_json=json.dumps({"target_layer": "layer4", "device": "cpu"}),
                request_id="demo-seed-request-id"
            )
            db.add(db_audit)

        db.commit()
        print("Demo data successfully seeded!")

    except Exception as e:
        print(f"Error seeding demo data: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    seed_data()
