import json
from typing import Dict, Any, Optional


class MedicalPromptBuilder:
    """
    Constructs structured prompts for Gemini LLM report generation.
    Enforces strict diagnostic boundaries (the PyTorch model determines the diagnosis; Gemini formats the report).
    """
    
    SYSTEM_INSTRUCTIONS = (
        "You are an expert AI Radiologist Assistant for MediVision AI. "
        "CRITICAL RULE: You MUST NOT alter, invent, or challenge the diagnosis provided. "
        "The primary diagnosis was computed by an automated PyTorch Deep Learning computer vision model. "
        "Your sole task is to synthesize a professional, highly structured AI-assisted medical report based on the provided parameters. "
        "You MUST return ONLY valid JSON matching the exact specified schema. Do not include markdown codeblock backticks."
    )

    @classmethod
    def build_prompt(
        cls,
        prediction_class: str,
        confidence_score: float,
        probabilities: Optional[Dict[str, float]],
        gradcam_explanation: Optional[str],
        modality: str = "X-Ray",
        patient_id: Optional[str] = None
    ) -> str:
        
        prob_str = json.dumps(probabilities) if probabilities else "N/A"
        patient_info = patient_id if patient_id else "Anonymous"

        prompt = f"""{cls.SYSTEM_INSTRUCTIONS}

INPUT DIAGNOSTIC DATA:
- Patient ID: {patient_info}
- Imaging Modality: {modality}
- PyTorch AI Primary Prediction: {prediction_class}
- Primary Model Confidence Score: {round(confidence_score * 100, 2)}%
- Full Class Probability Distribution: {prob_str}
- Grad-CAM Spatial Heatmap Summary: {gradcam_explanation or 'Standard uniform thoracic activation pattern.'}

REQUIRED JSON OUTPUT FORMAT:
{{
  "summary": "<1-2 sentence executive overview summarizing the imaging evaluation>",
  "findings": "<Detailed radiographic description of thoracic structures, focal opacities, or lack thereof>",
  "interpretation": "<Diagnostic interpretation explaining how the deep learning model confidence and Grad-CAM spatial heatmaps correlate with the final assessment>",
  "recommendations": [
      "<First clinical recommendation e.g. clinical correlation, follow-up imaging, or specialist consult>",
      "<Second clinical recommendation>",
      "<Third clinical recommendation>"
  ],
  "disclaimer": "This report is generated by an artificial intelligence system (MediVision AI) for decision-support purposes only. It does not constitute a definitive medical diagnosis and must be reviewed by a qualified licensed radiologist or physician."
}}

Return ONLY the raw JSON object.
"""
        return prompt
